
@startuml Examens

hide circle
hide empty members
hide empty methods


class Etudient {  
  numero
  nom
  prenom
  dateNaissance  
  }

class Examens {  
 date
 coefficient  
  }

class Note {
  note  
  }

class Cours{
  titre
  code de module  
  }
class Enseignants{
  nom
  prenom  
  }

Etudient "*" -- "1..*" Cours
Examens "*" -- "1" Cours
Etudient "1..*" -- "1..*" Examens
(Etudient, Examens) . Note
Enseignants "*" -- "*" Cours



@enduml
